- name: testing reister variable
  hosts: localhost
  tasks:
    - name: creat a user
      become: true
      ansible.builtin.user:
        name: ganesh
      register: myuser

    - name: fetch user data from register variable
      debug:
        msg: "{{myuser}}"

