- name: check if directory exists
  shell: "{{JENKINS_CLI_PREFIX}} get-job {{item.name}}"
  ignore_errors: true
  register: check_dir

- name: update directory template
  template:
    src: folder-template.xml
    dest: /tmp/folder-template.xml

- name: Create a directory
  when: check_dir.rc == 3
  shell: "cat /tmp/folder-template.xml | {{JENKINS_CLI_PREFIX}} create-job {{item.name}}"
  register: dir_name

- name: print dir name
  debug:
    msg: "{{dir_name}}"

- name: Update a directory
  when: check_dir.rc == 0
  shell: "cat /tmp/folder-template.xml | {{JENKINS_CLI_PREFIX}} update-job {{item.name}}"
  register: dir_name

