- name: Check jenkins connection
  shell: "{{JENKINS_CLI_PREFIX}} who-am-i"

- name: create jenkins folder
  include_tasks: folders-job.yml
  loop:
    - { name: "CI-pipelines", description: "All CI pipelines" }

- name: create jenkins multibranch pipelines
  include_tasks: mb-job.yml
  loop:
    - {name: "catalogue", repoName: "catalogue", dirName: "CI-pipelines/"}
    - {name: "cart", repoName: "cart", dirName: "CI-pipelines/"}
    - {name: "user", repoName: "user", dirName: "CI-pipelines/"}