- name: Check jenkins connection
  shell: "{{JENKINS_CLI_PREFIX}} who-am-i"

- name: create jenkins folder
  include_tasks: folders-job.yml
  loop:
    - { name: "CI-pipelines", description: "All CI pipelines" }
    - { name: "Terraform", description: "All Terraform pipelines" }

- name: create jenkins multibranch pipelines
  include_tasks: mb-job.yml
  loop: "{{MY_JOBS}}"

- name: create jenkins pipeline
  include_tasks: pipeline-job.yml
  loop: "{{PIPELINE_JOBS}}"